// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvvkIvRjH91GYQiIWh-O-sZVSqzJNdrf4',
    appId: '1:195377435516:web:52b70c56017d6af4c84af9',
    messagingSenderId: '195377435516',
    projectId: 'melangua-efaz',
    authDomain: 'melangua-efaz.firebaseapp.com',
    storageBucket: 'melangua-efaz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTxkjWT-6iepI92imCCegvDeWbvte62Y',
    appId: '1:195377435516:android:0d18270a98ee0f84c84af9',
    messagingSenderId: '195377435516',
    projectId: 'melangua-efaz',
    storageBucket: 'melangua-efaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfZcc1s5GVgWGJYHoTPKud9f1AUfqzVg',
    appId: '1:195377435516:ios:bfdec0cbaca608fac84af9',
    messagingSenderId: '195377435516',
    projectId: 'melangua-efaz',
    storageBucket: 'melangua-efaz.firebasestorage.app',
    iosBundleId: 'dev.melangua.learnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfZcc1s5GVgWGJYHoTPKud9f1AUfqzVg',
    appId: '1:195377435516:ios:bfdec0cbaca608fac84af9',
    messagingSenderId: '195377435516',
    projectId: 'melangua-efaz',
    storageBucket: 'melangua-efaz.firebasestorage.app',
    iosBundleId: 'dev.melangua.learnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvvkIvRjH91GYQiIWh-O-sZVSqzJNdrf4',
    appId: '1:195377435516:web:ff2a30552911dbb2c84af9',
    messagingSenderId: '195377435516',
    projectId: 'melangua-efaz',
    authDomain: 'melangua-efaz.firebaseapp.com',
    storageBucket: 'melangua-efaz.firebasestorage.app',
  );

}